# Generated by Django 4.2.3 on 2023-07-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_username_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='swo1asdP23r54', max_length=35, verbose_name='код верификации'),
        ),
    ]
