# Generated by Django 4.2.3 on 2023-07-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(default='Pas2osd31w54r', max_length=35, verbose_name='код верификации'),
        ),
    ]
