# Generated by Django 4.2.3 on 2023-07-27 09:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='почта')),
                ('name', models.CharField(max_length=250, verbose_name='имя')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, default=datetime.time(12, 35, 0, 33561), null=True, verbose_name='время')),
                ('date', models.DateField(auto_now=True, verbose_name='дата')),
                ('period', models.CharField(choices=[('день', 'день'), ('неделя', 'неделя'), ('месяц', 'месяц')], max_length=20, verbose_name='Период отправки')),
                ('status', models.CharField(choices=[('создано', 'создано'), ('в процессе', 'в процессе'), ('завершено', 'завершено')], default='завершено', max_length=20, verbose_name='Статус рассылки')),
                ('clients', models.ManyToManyField(to='clients.client', verbose_name='Принадлежит к клиенту:')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500, verbose_name='Заголовок сообщения')),
                ('body', models.TextField(verbose_name='Тело сообщения')),
                ('mailings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.mailings')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_q', models.DateTimeField(auto_now_add=True, verbose_name='попытка отправления')),
                ('status', models.CharField(choices=[('завершено', 'завершено'), ('неудачно', 'неудачно'), ('в процессе', 'в процессе')], max_length=25, verbose_name='статус')),
                ('answer_server', models.BooleanField(verbose_name='ответ сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.mailings', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
